method: grid
metric:
  name: orig_loss
  goal: minimize
parameters:
  lr:
    values: [1.0e-6, 1.0e-5, 1.0e-4]
  weight_decay:
    values: [0.01, 0.1]
  temperature:
    values: [0.5, 1.0, 5.0, 10.0]
  max_train_epochs: 
    values: [20]
