method: random
metric:
  name: orig_loss
  goal: minimize
parameters:
  lr:
    distribution: log_uniform_values
    min: 1.0e-7
    max: 1.0e-4
  weight_decay:
    values: [0.01, 0.1]
  temperature:
    min: 0.5
    max: 10.0
  max_train_epochs: 
    values: [20]
