## data
train_file: downloads/data/retriever/nq-train.json
dev_file: downloads/data/retriever/nq-dev.json


## training
lr: 1.0e-5
weight_decay: 0.1
temperature: 5.0
max_train_epochs: 40
base_model: bert-base-uncased
num_workers: 8
per_device_train_batch_size: 32
per_device_eval_batch_size: 32
adam_eps: 1.0e-8
max_grad_norm: 2.0
warmup_steps: 1237
seed: 26
gradient_accumulation_steps: 1
val_check_interval: 1.0
